### PR TITLE
Sort list by subscriber count

### PR DESCRIPTION
**Pull request by stephensamra**
I decided to have a go at implementing the script discussed in #50. The `sort.php` script will:

- read the list of channels from `list.json`
- lookup the subscriber count for each channel
- rewrite `README.md` with the list of channels, sorted by subscriber count

To run the script, you'll need to get a YouTube API key and then run the script like so:

```bash
YOUTUBE_API_KEY="YOUR API KEY" php sort.php
```

Right now, the script needs the YouTube channel's ID in order to fetch the subscriber count, which is not ideal. I would say it could be tweaked to use the channel username instead.

The code is not perfect by any means, I was just hacking it together. It should be a good starting point, though.

### CODE REVIEW

**Comment by devfaysal** [comment]
How did you get the channel's ID from the handle? Is there any automated way? or did it manually?

**Comment by stephensamra** [comment]
> channel username != channel handle

Interesting, thanks for the info @devfaysal. I'll update the code to use `youtube_handle` since it's more appropriate.

> How did you get the channel's ID from the handle?

I did it manually by viewing page source and then searching for `rss` which shows the ID on the RSS feed's URL. You can also find it by searching for `externalId`.

image
image

**Comment by devfaysal** [comment]
I found a way to get the channel ID from the handle, but not perfect
`$url = 'https://youtube.googleapis.com/youtube/v3/search?part=snippet&maxResults=25&q=%40' . $handle . '&type=handle&key=' . $api_key;`

This is actually using the search and might return multiple result.

**Comment by stephensamra** [comment]
I agree and thanks for looking into it, @devfaysal. Hopefully the API adds support for handles in future. Would make things a lot easier.

**Comment by nunomaduro** [comment]
Thanks! Using https://github.com/php-youtubers/directory/pull/61 after reviewing.

**Pull request closed without merging**
