### PR TITLE
Sort the list by YouTube followers count.

### PR DESCRIPTION
**Pull request by hrsa**
It works, ~~but it is rather slow, since it uses an external solution (https://yt.lemnoslife.com/channels?handle= ... )~~ to get youtubers' channel id.

UPD: now its faster and doesn't use any external solutions!

### CODE REVIEW

**Comment by Joeri-Abbo** [comment]
@hrsa You api token is exposed. Maybe use a dotenv or arg for this so it wont expose the token? 
Maybe with python it could be a lot faster with concurrent processing the rows?

**Comment by hrsa** [comment]
yep, i just generated a free token for the sake of easily testing that, i'll take it down in a couple of days!

**Comment by Joeri-Abbo** [comment]
@hrsa Please review my alternative in python it is because of async faster and can be runned on github actions 
https://github.com/php-youtubers/directory/pull/62

**Comment by Joeri-Abbo** [comment]
> yep, i just generated a free token for the sake of easily testing that, i'll take it down in a couple of days!

Better safe then sorry in token commits 😄

**Comment by nunomaduro** [comment]
Thanks!

**Pull request merged**
