### PR TITLE
Add ProgramWithGio youtube channel

### PR DESCRIPTION
**Pull request by the-dijkstra**
Add https://www.youtube.com/@ProgramWithGio

### CODE REVIEW

**Comment by bajoski34** [comment]
i agree

**Review by hrsa — APPROVED** [review]
42.6K subscribers
168 videos
Last video 1 month ago

Language: English

**Comment by hrsa** [comment]
@the-dijkstra could you please add his full name and posifion, like Full Name ‧ Developer at Company  or Full Name ‧ Founder of Product Name ?
I've tried to search for it, but couldn't find anything :(

**Comment by the-dijkstra** [comment]
I couldn't find his name neither, I will reach out to him on twitter.

**Comment by hrsa** [comment]
I added him from another request, so i'll close this one for now... Thanks for helping out and feel free to submit a new one as soon as you get new info, alright?

**Pull request closed without merging**
