### PR TITLE
Add cron to update stats

### PR DESCRIPTION
**Pull request by simonhamp**
This simply adds a GitHub Action that should update the stats every Monday.

It requires you to set an `YOUTUBE_API_KEY` secret, which you should be able to do [here](https://github.com/php-youtubers/directory/settings/secrets/actions)

When the cron runs it will PR the updates, so it should be a simple case of merging the PR to keep the list up to date

### CODE REVIEW

**Comment by nunomaduro** [comment]
@hrsa can you check this? looks dope.

**Comment by hrsa** [comment]
@nunomaduro it is! I'd love to but I have no access to my laptop until Sunday evening, I can take a look soon 👍

**Comment by simonhamp** [comment]
@hrsa You can see an example of the result [here](https://github.com/simonhamp/directory/pull/2)

**Comment by simonhamp** [comment]
Made a few improvements to this just to make it a bit more reliable. It now:
- Uses the `gh` CLI to create the PR (the action that it used has been archived)
- Dynamically names the branch like `stats_{Y-m-d}` so that if you aren't able to approve the PRs each week, you won't get failed runs (any unmerged, old PRs from this process can likely just be closed and the branches deleted)

**Comment by simonhamp** [comment]
@hrsa @nunomaduro anything I can do to help get this one over the line?

**Comment by hrsa** [comment]
@simonhamp sorry for the delay, that's a great contribution ! 💪
@nunomaduro i've tested it out and it works well. but before merging - either you would have to add the API key to the secrets, or i would need admin access to do that :)

**Comment by nunomaduro** [comment]
You are now admin.

**Comment by hrsa** [comment]
@nunomaduro we also need to modify the permissions for the workflow, since it creates PRs:
https://github.com/php-youtubers/directory/settings/actions
The options are greyed out for me, i guess that only you can modify that

**Comment by hrsa** [comment]
@nunomaduro still need you here :)

> @nunomaduro we also need to modify the permissions for the workflow, since it creates PRs: https://github.com/php-youtubers/directory/settings/actions The options are greyed out for me, i guess that only you can modify that

**Pull request merged**
